<div class="product">
    <?php 
        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('demo-widgets')->toHtml();
    ?>
</div>

<script>
require(['jquery', 'slick'], function($) {
    $(document).ready(function() {
        $(".product-items").slick({
            infinite: true,
            slidesToShow: 7,
            slidesToScroll: 7,
            arrows: false,
            swipeToSlide: true,
            responsive: [{
                    breakpoint: 1746,
                    settings: {
                        slidesToShow: 6,
                        slidesToScroll: 6,
                        infinite: true,
                    }
                }, {
                    breakpoint: 1511,
                    settings: {
                        slidesToShow: 5,
                        slidesToScroll: 5,
                        infinite: true,
                    }
                }, {
                    breakpoint: 1270,
                    settings: {
                        slidesToShow: 4,
                        slidesToScroll: 4,
                        infinite: true,
                    }
                }, {
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3,
                        infinite: true,
                    }
                },
                {
                    breakpoint: 768,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2,
                        infinite: true,
                    }
                },
                {
                    breakpoint: 640,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2,
                        infinite: true,
                    }
                },
                {
                    breakpoint: 528,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1,
                        infinite: true,
                    }
                }
            ]
        });
    });
});
</script>